<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class ClubSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('clubs')->insert(array(
            array(
                'tournement_id' => 1,
                'club_nr' => 1,
                'club_name' => 'SC Loppersum',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'tournement_id' => 1,
                'club_nr' => 2,
                'club_name' => 'VV Middelstum',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'tournement_id' => 1,
                'club_nr' => 3,
                'club_name' => 'VV Stedum',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'tournement_id' => 1,
                'club_nr' => 4,
                'club_name' => 'VV Siddeburen',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 9,
                'tournement_id' => 4,
                'club_nr' => 1,
                'club_name' => 'Ba',
                'club_played' => 8,
                'club_points' => 12,
                'club_win' => 4,
                'club_draw' => 0,
                'club_loss' => 4,
                'club_goalagainst' => 20,
                'club_goal' => 87,
                'club_goaldifference'=> 67,
                'club_ranking' => 8,
                'club_average' => 1.50,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 10,
                'tournement_id' => 4,
                'club_nr' => 2,
                'club_name' => 'Bb',
                'club_played' => 9,
                'club_points' => 15,
                'club_win' => 5,
                'club_draw' => 0,
                'club_loss' => 4,
                'club_goalagainst' => 136,
                'club_goal' => 36,
                'club_goaldifference'=> -100,
                'club_ranking' => 5,
                'club_average' => 1.67,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 11,
                'tournement_id' => 4,
                'club_nr' => 3,
                'club_name' => 'Ka',
                'club_played' => 18,
                'club_points' => 25,
                'club_win' => 8,
                'club_draw' => 1,
                'club_loss' => 9,
                'club_goalagainst' => 122,
                'club_goal' => 128,
                'club_goaldifference'=> 6,
                'club_ranking' => 10,
                'club_average' => 1.39,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 12,
                'tournement_id' => 4,
                'club_nr' => 4,
                'club_name' => 'Kb',
                'club_played' => 18,
                'club_points' => 22,
                'club_win' => 7,
                'club_draw' => 1,
                'club_loss' => 10,
                'club_goalagainst' => 110,
                'club_goal' => 128,
                'club_goaldifference'=> 18,
                'club_ranking' => 13,
                'club_average' => 1.22,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 13,
                'tournement_id' => 4,
                'club_nr' => 5,
                'club_name' => 'Kc',
                'club_played' => 12,
                'club_points' => 13,
                'club_win' => 4,
                'club_draw' => 1,
                'club_loss' => 7,
                'club_goalagainst' => 60,
                'club_goal' => 99,
                'club_goaldifference'=> 39,
                'club_ranking' => 15,
                'club_average' => 1.08,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 14,
                'tournement_id' => 4,
                'club_nr' => 6,
                'club_name' => 'Ma',
                'club_played' => 22,
                'club_points' => 38,
                'club_win' => 12,
                'club_draw' => 2,
                'club_loss' => 8,
                'club_goalagainst' => 108,
                'club_goal' => 154,
                'club_goaldifference'=> 46,
                'club_ranking' => 3,
                'club_average' => 1.73,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 15,
                'tournement_id' => 4,
                'club_nr' => 7,
                'club_name' => 'Mb',
                'club_played' => 18,
                'club_points' => 23,
                'club_win' => 7,
                'club_draw' => 2,
                'club_loss' => 9,
                'club_goalagainst' => 112,
                    'club_goal' => 94,
                'club_goaldifference'=> -18,
                'club_ranking' => 12,
                'club_average' => 1.28,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 16,
                'tournement_id' => 4,
                'club_nr' => 8,
                'club_name' => 'MMH6a',
                'club_played' => 18,
                'club_points' => 25,
                'club_win' => 8,
                'club_draw' => 1,
                'club_loss' => 9,
                'club_goalagainst' => 152,
                'club_goal' => 80,
                'club_goaldifference'=> -72,
                'club_ranking' => 11,
                'club_average' => 1.39,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 17,
                'tournement_id' => 4,
                'club_nr' => 9,
                'club_name' => 'MH6a',
                'club_played' => 16,
                'club_points' => 11,
                'club_win' => 3,
                'club_draw' => 2,
                'club_loss' => 11,
                'club_goalagainst' => 204,
                'club_goal' => 54,
                'club_goaldifference'=> -150,
                'club_ranking' => 16,
                'club_average' => 0.69,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 18,
                'tournement_id' => 4,
                'club_nr' => 10,
                'club_name' => 'Ha',
                'club_played' => 22,
                'club_points' => 40,
                'club_win' => 13,
                'club_draw' => 1,
                'club_loss' => 8,
                'club_goalagainst' => 77,
                'club_goal' => 182,
                'club_goaldifference'=> 105,
                'club_ranking' => 2,
                'club_average' => 1.82,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 19,
                'tournement_id' => 4,
                'club_nr' => 11,
                'club_name' => 'Hb',
                'club_played' => 22,
                'club_points' => 25,
                'club_win' => 7,
                'club_draw' => 4,
                'club_loss' => 11,
                'club_goalagainst' => 146,
                'club_goal' => 120,
                'club_goaldifference'=> -26,
                'club_ranking' => 14,
                'club_average' => 1.14,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 20,
                'tournement_id' => 4,
                'club_nr' => 12,
                'club_name' => 'Hc',
                'club_played' => 23,
                'club_points' => 36,
                'club_win' => 11,
                'club_draw' => 3,
                'club_loss' => 9,
                'club_goalagainst' => 102,
                'club_goal' => 138,
                'club_goaldifference'=> 36,
                'club_ranking' => 7,
                'club_average' => 1.57,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 21,
                'tournement_id' => 4,
                'club_nr' => 13,
                'club_name' => 'Hd',
                'club_played' => 22,
                'club_points' => 35,
                'club_win' => 11,
                'club_draw' => 2,
                'club_loss' => 9,
                'club_goalagainst' => 109,
                'club_goal' => 107,
                'club_goaldifference'=> -2,
                'club_ranking' => 6,
                'club_average' => 1.59,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 22,
                'tournement_id' => 4,
                'club_nr' => 14,
                'club_name' => 'Va',
                'club_played' => 13,
                'club_points' => 24,
                'club_win' => 8,
                'club_draw' => 0,
                'club_loss' => 5,
                'club_goalagainst' => 39,
                'club_goal' => 126,
                'club_goaldifference'=> 87,
                'club_ranking' => 1,
                'club_average' => 1.85,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 23,
                'tournement_id' => 4,
                'club_nr' => 15,
                'club_name' => 'Vb',
                'club_played' => 21,
                'club_points' => 36,
                'club_win' => 11,
                'club_draw' => 3,
                'club_loss' => 7,
                'club_goalagainst' => 139,
                'club_goal' => 87,
                'club_goaldifference'=> -52,
                'club_ranking' => 4,
                'club_average' => 1.71,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 24,
                'tournement_id' => 4,
                'club_nr' => 16,
                'club_name' => 'TTO',
                'club_played' => 18,
                'club_points' => 26,
                'club_win' => 7,
                'club_draw' => 5,
                'club_loss' => 6,
                'club_goalagainst' => 62,
                'club_goal' => 78,
                'club_goaldifference'=> 16,
                'club_ranking' => 9,
                'club_average' => 1.44,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            )
        ));
    }
}
