<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class TeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('teams')->insert(array(
            array(
                'poule_id' => 1,
                'club_id' => 1,
                'team_nr' => 1,
                'team_name' => 'SC Loppersum JO19-1',
                'points' => 3,
                'played' => 5,
                'win' => 1,
                'draw' => 0,
                'loss' => 4,
                'goal' => 6,
                'goalagainst' => 8,
                'goaldifference' => -2,
                'team_ranking' => 5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'poule_id' => 1,
                'club_id' => 2,
                'team_nr' => 2,
                'team_name' => 'Middelstum JO19-1',
                'points' => 8,
                'played' => 5,
                'win' => 2,
                'draw' => 2,
                'loss' => 1,
                'goal' => 4,
                'goalagainst' => 3,
                'goaldifference' => 1,
                'team_ranking' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'poule_id' => 1,
                'club_id' => 4,
                'team_nr' => 3,
                'team_name' => 'Siddeburen JO19-1',
                'points' => 12,
                'played' => 5,
                'win' => 4,
                'draw' => 0,
                'loss' => 1,
                'goal' => 11,
                'goalagainst' => 4,
                'goaldifference' => 7,
                'team_ranking' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'poule_id' => 1,
                'club_id' => 3,
                'team_nr' => 4,
                'team_name' => 'STEO JO19-1',
                'points' => 1,
                'played' => 5,
                'win' => 0,
                'draw' => 1,
                'loss' => 4,
                'goal' => 0,
                'goalagainst' => 13,
                'goaldifference' => -13,
                'team_ranking' => 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'poule_id' => 1,
                'club_id' => 2,
                'team_nr' => 5,
                'team_name' => 'Middelstum JO19-2',
                'points' => 6,
                'played' => 5,
                'win' => 2,
                'draw' => 0,
                'loss' => 3,
                'goal' => 7,
                'goalagainst' => 12,
                'goaldifference' => -5,
                'team_ranking' => 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'poule_id' => 1,
                'club_id' => 1,
                'team_nr' => 6,
                'team_name' => 'SC Loppersum JO19-2',
                'points' => 13,
                'played' => 5,
                'win' => 4,
                'draw' => 1,
                'loss' => 0,
                'goal' => 15,
                'goalagainst' => 3,
                'goaldifference' => 12,
                'team_ranking' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'poule_id' => 1,
                'club_id' => 1,
                'team_nr' => 6,
                'team_name' => 'SC Loppersum JO19-2',
                'points' => 13,
                'played' => 5,
                'win' => 4,
                'draw' => 1,
                'loss' => 0,
                'goal' => 15,
                'goalagainst' => 3,
                'goaldifference' => 12,
                'team_ranking' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 53,
                'poule_id' => 10,
                'club_id' => 18,
                'team_nr' => 1,
                'team_name' => 'Ha1',
                'played' => 5,
                'points' => 9,
                'win' => 3,
                'draw' => 0,
                'loss' => 2,
                'goalagainst' => 16,
                'goal' => 42,
                'goaldifference' => 26,
                'team_ranking' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 54,
                'poule_id' => 10,
                'club_id' => 20,
                'team_nr' => 2,
                'team_name' => 'Hc1',
                'played' => 5,
                'points' => 4,
                'win' => 1,
                'draw' => 1,
                'loss' => 3,
                'goalagainst' => 34,
                'goal' => 20,
                'goaldifference' => -14,
                'team_ranking' => 5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 55,
                'poule_id' => 10,
                'club_id' => 15,
                'team_nr' => 3,
                'team_name' => 'Mb1',
                'played' => 5,
                'points' => 7,
                'win' => 2,
                'draw' => 1,
                'loss' => 2,
                'goalagainst' => 28,
                'goal' => 28,
                'goaldifference' => 0,
                'team_ranking' => 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 56,
                'poule_id' => 10,
                'club_id' => 24,
                'team_nr' => 4,
                'team_name' => 'TTO3',
                'played' => 5,
                'points' => 7,
                'win' => 2,
                'draw' => 1,
                'loss' => 2,
                'goalagainst' => 14,
                'goal' => 19,
                'goaldifference' => 5,
                'team_ranking' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 57,
                'poule_id' => 10,
                'club_id' => 16,
                'team_nr' => 5,
                'team_name' => 'MMH6a2',
                'played' => 5,
                'points' => 4,
                'win' => 1,
                'draw' => 1,
                'loss' => 3,
                'goalagainst' => 40,
                'goal' => 19,
                'goaldifference' => -21,
                'team_ranking' => 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 58,
                'poule_id' => 10,
                'club_id' => 11,
                'team_nr' => 6,
                'team_name' => 'Ka1',
                'played' => 5,
                'points' => 12,
                'win' => 4,
                'draw' => 0,
                'loss' => 1,
                'goalagainst' => 26,
                'goal' => 30,
                'goaldifference' => 4,
                'team_ranking' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 59,
                'poule_id' => 11,
                'club_id' => 14,
                'team_nr' => 7,
                'team_name' => 'Ma1',
                'played' => 5,
                'points' => 3,
                'win' => 1,
                'draw' => 0,
                'loss' => 4,
                'goalagainst' => 54,
                'goal' => 22,
                'goaldifference' => -32,
                'team_ranking' => 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 60,
                'poule_id' => 11,
                'club_id' => 21,
                'team_nr' => 8,
                'team_name' => 'Hd2',
                'played' => 5,
                'points' => 10,
                'win' => 3,
                'draw' => 1,
                'loss' => 1,
                'goalagainst' => 22,
                'goal' => 19,
                'goaldifference' => -3,
                'team_ranking' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 61,
                'poule_id' => 11,
                'club_id' => 16,
                'team_nr' => 9,
                'team_name' => 'MMH6a1',
                'played' => 5,
                'points' => 6,
                'win' => 2,
                'draw' => 0,
                'loss' => 3,
                'goalagainst' => 46,
                'goal' => 10,
                'goaldifference' => -36,
                'team_ranking' => 5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 62,
                'poule_id' => 11,
                'club_id' => 19,
                'team_nr' => 10,
                'team_name' => 'Hb2',
                'played' => 5,
                'points' => 7,
                'win' => 2,
                'draw' => 1,
                'loss' => 2,
                'goalagainst' => 30,
                'goal' => 20,
                'goaldifference' => -10,
                'team_ranking' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 63,
                'poule_id' => 11,
                'club_id' => 12,
                'team_nr' => 11,
                'team_name' => 'Kb1',
                'played' => 5,
                'points' => 6,
                'win' => 2,
                'draw' => 0,
                'loss' => 3,
                'goalagainst' => 18,
                'goal' => 52,
                'goaldifference' => 34,
                'team_ranking' => 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 64,
                'poule_id' => 11,
                'club_id' => 22,
                'team_nr' => 12,
                'team_name' => 'Va1',
                'played' => 5,
                'points' => 12,
                'win' => 4,
                'draw' => 0,
                'loss' => 1,
                'goalagainst' => 7,
                'goal' => 54,
                'goaldifference' => 47,
                'team_ranking' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 65,
                'poule_id' => 12,
                'club_id' => 23,
                'team_nr' => 13,
                'team_name' => 'Vb1',
                'played' => 5,
                'points' => 10,
                'win' => 3,
                'draw' => 1,
                'loss' => 1,
                'goalagainst' => 32,
                'goal' => 37,
                'goaldifference' => 5,
                'team_ranking' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 66,
                'poule_id' => 12,
                'club_id' => 18,
                'team_nr' => 14,
                'team_name' => 'Ha2',
                'played' => 5,
                'points' => 6,
                'win' => 2,
                'draw' => 0,
                'loss' => 3,
                'goalagainst' => 27,
                'goal' => 34,
                'goaldifference' => 7,
                'team_ranking' => 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 67,
                'poule_id' => 12,
                'club_id' => 20,
                'team_nr' => 15,
                'team_name' => 'Hc2',
                'played' => 5,
                'points' => 12,
                'win' => 4,
                'draw' => 0,
                'loss' => 1,
                'goalagainst' => 2,
                'goal' => 56,
                'goaldifference' => 54,
                'team_ranking' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 68,
                'poule_id' => 12,
                'club_id' => 10,
                'team_nr' => 16,
                'team_name' => 'Bb1',
                'played' => 5,
                'points' => 6,
                'win' => 2,
                'draw' => 0,
                'loss' => 3,
                'goalagainst' => 78,
                'goal' => 20,
                'goaldifference' => -58,
                'team_ranking' => 5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 69,
                'poule_id' => 12,
                'club_id' => 11,
                'team_nr' => 17,
                'team_name' => 'Ka2',
                'played' => 5,
                'points' => 3,
                'win' => 1,
                'draw' => 0,
                'loss' => 4,
                'goalagainst' => 32,
                'goal' => 20,
                'goaldifference' => -12,
                'team_ranking' => 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 70,
                'poule_id' => 12,
                'club_id' => 15,
                'team_nr' => 18,
                'team_name' => 'Mb4',
                'played' => 5,
                'points' => 7,
                'win' => 2,
                'draw' => 1,
                'loss' => 2,
                'goalagainst' => 28,
                'goal' => 32,
                'goaldifference' => 4,
                'team_ranking' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 71,
                'poule_id' => 13,
                'club_id' => 19,
                'team_nr' => 19,
                'team_name' => 'Hb1',
                'played' => 5,
                'points' => 5,
                'win' => 1,
                'draw' => 2,
                'loss' => 2,
                'goalagainst' => 26,
                'goal' => 22,
                'goaldifference' => -4,
                'team_ranking' => 5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 72,
                'poule_id' => 13,
                'club_id' => 14,
                'team_nr' => 20,
                'team_name' => 'Ma2',
                'played' => 5,
                'points' => 7,
                'win' => 2,
                'draw' => 1,
                'loss' => 2,
                'goalagainst' => 10,
                'goal' => 22,
                'goaldifference' => 12,
                'team_ranking' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 73,
                'poule_id' => 13,
                'club_id' => 12,
                'team_nr' => 21,
                'team_name' => 'Kb2',
                'played' => 5,
                'points' => 6,
                'win' => 2,
                'draw' => 0,
                'loss' => 3,
                'goalagainst' => 56,
                'goal' => 14,
                'goaldifference' => -42,
                'team_ranking' => 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 74,
                'poule_id' => 13,
                'club_id' => 20,
                'team_nr' => 22,
                'team_name' => 'Hc3',
                'played' => 5,
                'points' => 10,
                'win' => 3,
                'draw' => 1,
                'loss' => 1,
                'goalagainst' => 6,
                'goal' => 34,
                'goaldifference' => 28,
                'team_ranking' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 75,
                'poule_id' => 13,
                'club_id' => 24,
                'team_nr' => 23,
                'team_name' => 'TTO4',
                'played' => 5,
                'points' => 9,
                'win' => 2,
                'draw' => 3,
                'loss' => 0,
                'goalagainst' => 12,
                'goal' => 18,
                'goaldifference' => 6,
                'team_ranking' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id' => 76,
                'poule_id' => 13,
                'club_id' => 21,
                'team_nr' => 24,
                'team_name' => 'Hd3',
                'played' => 5,
                'points' => 4,
                'win' => 1,
                'draw' => 1,
                'loss' => 3,
                'goalagainst' => 24,
                'goal' => 24,
                'goaldifference' => 0,
                'team_ranking' => 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
        ));
    }
}
